"""IntelAI domain glossary — authoritative, sourced definitions for every metric,
KPI and abbreviation the copilot reasons about.

Purpose (STRATEGY §"no hallucination, grounded, research-credible"):
  * Grounds the RAG — these definitions are seeded as knowledge docs so the copilot
    cites a real, vetted source instead of improvising ("explain each term clearly").
  * Powers the per-page contextual explainer in the UI (term → meaning + formula +
    how to read it + a 2026 benchmark).

Definitions/benchmarks were cross-checked against 2026 industry references (DORA,
GHG Protocol/CSRD ESRS E1, SaaS benchmark reports, AIHR people-analytics, manufacturing
OEE/TRIR guidance, supply-chain perfect-order literature). Each entry keeps a short
`source` tag naming the standard/body it follows so answers stay credentialed.

Schema per term:
  domain        – one of the 7 domains (+ "Method" for the AI/analytics concepts)
  abbr          – common abbreviation/acronym (or None)
  definition    – one/two-sentence plain-language meaning
  formula       – how it is computed (or None for qualitative terms)
  direction     – "up" = higher is better, "down" = lower is better, None = contextual
  benchmark     – what "good" looks like in 2026 (concise)
  source        – the standard/authority the definition follows
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional

# ── The glossary. Keys match seed KPI metric names exactly where applicable. ──
GLOSSARY: Dict[str, Dict[str, Any]] = {
    # ───────────────────────── Finance ─────────────────────────
    "Revenue": {
        "domain": "Finance", "abbr": None,
        "definition": "Total income from goods/services sold in a period, before any costs are deducted (top line).",
        "formula": "Σ (units sold × price)", "direction": "up",
        "benchmark": "Growth vs prior period matters more than the absolute; SaaS targets 2–3%+ MoM.",
        "source": "GAAP/IFRS revenue recognition",
    },
    "Gross Margin": {
        "domain": "Finance", "abbr": "GM",
        "definition": "Share of revenue left after the direct cost of delivering the product (COGS).",
        "formula": "(Revenue − COGS) / Revenue × 100", "direction": "up",
        "benchmark": "Software 70–85%; >75% is healthy. Below 50% pressures everything downstream.",
        "source": "GAAP/IFRS",
    },
    "EBITDA": {
        "domain": "Finance", "abbr": "EBITDA",
        "definition": "Earnings Before Interest, Taxes, Depreciation & Amortization — a proxy for core operating profitability.",
        "formula": "Net Profit + Interest + Taxes + Depreciation + Amortization", "direction": "up",
        "benchmark": "Positive and rising; EBITDA margin (EBITDA/Revenue) >20% is strong.",
        "source": "Corporate finance standard",
    },
    "Operating Costs": {
        "domain": "Finance", "abbr": "OpEx",
        "definition": "Ongoing costs of running the business (salaries, rent, software, sales & marketing) excluding COGS.",
        "formula": "Σ operating expenses", "direction": "down",
        "benchmark": "Should grow slower than revenue (operating leverage).",
        "source": "GAAP/IFRS",
    },
    "Net Profit": {
        "domain": "Finance", "abbr": None,
        "definition": "What remains after all costs, interest and taxes (bottom line).",
        "formula": "Revenue − all costs − interest − taxes", "direction": "up",
        "benchmark": "Net margin >10% is solid for most sectors.",
        "source": "GAAP/IFRS",
    },
    "Operating Cash Flow": {
        "domain": "Finance", "abbr": "OCF",
        "definition": "Cash generated by normal operations — the truest test of whether the business funds itself.",
        "formula": "Net income + non-cash items ± working-capital changes", "direction": "up",
        "benchmark": "Positive and trending up; should track EBITDA over time.",
        "source": "IAS 7 / ASC 230",
    },
    "Rule of 40": {
        "domain": "Finance", "abbr": None,
        "definition": "Heuristic that a healthy software company's growth rate plus profit margin should be at least 40%.",
        "formula": "Revenue growth % + profit (or EBITDA/FCF) margin % ≥ 40", "direction": "up",
        "benchmark": "≥40% healthy; >60% earns 2–3× valuation. Only ~11–30% of SaaS clear 40%.",
        "source": "SaaS benchmark reports 2026",
    },

    "COGS": {
        "domain": "Finance", "abbr": "COGS",
        "definition": "Cost of Goods Sold — the direct costs of producing/delivering what was sold in the period.",
        "formula": "Σ direct materials + direct labour + direct overhead", "direction": "down",
        "benchmark": "Revenue − COGS = gross profit; software keeps COGS low (high gross margin).",
        "source": "GAAP/IFRS",
    },
    "Taxes": {
        "domain": "Finance", "abbr": None,
        "definition": "Income taxes charged on pre-tax profit for the period.",
        "formula": "pre-tax income × effective tax rate", "direction": "down",
        "benchmark": "Track the effective tax rate; deducted to reach net profit.",
        "source": "GAAP/IFRS",
    },
    "Free Cash Flow": {
        "domain": "Finance", "abbr": "FCF",
        "definition": "Cash left after operating costs and capital expenditure — the cash actually available to investors/reinvestment.",
        "formula": "Operating Cash Flow − CapEx", "direction": "up",
        "benchmark": "Positive and growing; FCF margin >10% is strong. Feeds the Rule of 40.",
        "source": "Corporate finance standard",
    },
    "Working Capital": {
        "domain": "Finance", "abbr": "WC",
        "definition": "Short-term liquidity cushion — current assets minus current liabilities.",
        "formula": "Current Assets − Current Liabilities", "direction": "up",
        "benchmark": "Positive funds day-to-day operations; watch the trend, not just the level.",
        "source": "Corporate finance standard",
    },
    "Days Sales Outstanding": {
        "domain": "Finance", "abbr": "DSO",
        "definition": "Average days to collect cash after a sale — how fast receivables convert to cash.",
        "formula": "(Accounts Receivable / Revenue) × days in period", "direction": "down",
        "benchmark": "Lower frees cash; <45 days is healthy for most B2B.",
        "source": "Corporate finance / working-capital 2026",
    },
    "Cash Runway": {
        "domain": "Finance", "abbr": None,
        "definition": "Months the company can operate at the current net burn before cash runs out.",
        "formula": "Cash balance / monthly net burn", "direction": "up",
        "benchmark": "18–24 months is the post-2023 norm investors expect before the next raise.",
        "source": "Startup finance benchmarks 2026",
    },

    # ───────────────────────── Growth ─────────────────────────
    "MRR": {
        "domain": "Growth", "abbr": "MRR",
        "definition": "Monthly Recurring Revenue — predictable subscription revenue normalised to a month.",
        "formula": "Σ active monthly subscription value", "direction": "up",
        "benchmark": "Track net new MRR (new + expansion − churn − contraction).",
        "source": "SaaS benchmark reports 2026",
    },
    "ARR": {
        "domain": "Growth", "abbr": "ARR",
        "definition": "Annual Recurring Revenue — the annualised run-rate of recurring revenue; the standard board/investor unit.",
        "formula": "MRR × 12", "direction": "up",
        "benchmark": "Smooths monthly noise; pair with growth rate and NRR.",
        "source": "SaaS benchmark reports 2026",
    },
    "Customer Count": {
        "domain": "Growth", "abbr": None,
        "definition": "Number of active paying customers/logos.",
        "formula": "count(active customers)", "direction": "up",
        "benchmark": "Read alongside revenue concentration and logo churn.",
        "source": "SaaS benchmark reports 2026",
    },
    "Churn Rate": {
        "domain": "Growth", "abbr": None,
        "definition": "Rate at which customers (logo churn) or revenue (revenue churn) is lost in a period.",
        "formula": "lost / starting base × 100", "direction": "down",
        "benchmark": "Monthly <3% excellent, >7% concerning. Track logo AND revenue churn.",
        "source": "SaaS benchmark reports 2026",
    },
    "CAC": {
        "domain": "Growth", "abbr": "CAC",
        "definition": "Customer Acquisition Cost — fully-loaded sales & marketing cost to win one new customer.",
        "formula": "(S&M spend) / new customers", "direction": "down",
        "benchmark": "Judge via CAC payback: <12 months elite, 15–18 median.",
        "source": "SaaS benchmark reports 2026",
    },
    "LTV": {
        "domain": "Growth", "abbr": "LTV",
        "definition": "Customer Lifetime Value — gross-margin profit expected from a customer over their lifetime.",
        "formula": "(ARPA × Gross Margin %) / churn rate", "direction": "up",
        "benchmark": "Always margin-adjusted; pair with CAC as a ratio.",
        "source": "SaaS benchmark reports 2026",
    },
    "LTV:CAC": {
        "domain": "Growth", "abbr": "LTV:CAC",
        "definition": "Ratio of lifetime value to acquisition cost — unit-economics efficiency of growth.",
        "formula": "LTV / CAC", "direction": "up",
        "benchmark": "Healthy 3:1–5:1; top companies >4:1.",
        "source": "SaaS benchmark reports 2026",
    },
    "Net Promoter Score": {
        "domain": "Growth", "abbr": "NPS",
        "definition": "Customer loyalty index from one question ('how likely to recommend?', 0–10); a leading churn/expansion indicator.",
        "formula": "% promoters (9–10) − % detractors (0–6)", "direction": "up",
        "benchmark": "B2B SaaS 30–40 solid; consumer 50+ healthy.",
        "source": "SaaS benchmark reports 2026",
    },
    "Net Revenue Retention": {
        "domain": "Growth", "abbr": "NRR",
        "definition": "Revenue kept and grown from the existing customer base (expansion − churn − contraction).",
        "formula": "(start MRR + expansion − churn − contraction) / start MRR × 100", "direction": "up",
        "benchmark": "Enterprise 110–120%+, SMB 100–110%. >100% means the base grows by itself.",
        "source": "SaaS benchmark reports 2026",
    },
    "CAC Payback": {
        "domain": "Growth", "abbr": None,
        "definition": "Months of gross profit needed to recover the cost of acquiring a customer.",
        "formula": "CAC / (new MRR × gross margin %)", "direction": "down",
        "benchmark": "<12 months elite, 15–18 median; the real test of CAC efficiency.",
        "source": "SaaS benchmark reports 2026",
    },
    "ARPU": {
        "domain": "Growth", "abbr": "ARPU",
        "definition": "Average Revenue Per User/Account — recurring revenue divided by active customers.",
        "formula": "MRR / active customers", "direction": "up",
        "benchmark": "Rising ARPU signals upsell/pricing power; read with churn.",
        "source": "SaaS benchmark reports 2026",
    },
    "Active Users": {
        "domain": "Growth", "abbr": "MAU/DAU",
        "definition": "Count of users active in a period (monthly = MAU, daily = DAU) — a core engagement signal.",
        "formula": "count(distinct active users in period)", "direction": "up",
        "benchmark": "DAU/MAU ratio (stickiness) >20% is good; >50% is exceptional.",
        "source": "Product analytics 2026",
    },

    # ───────────────────────── People (HR) ─────────────────────────
    "Headcount": {
        "domain": "People", "abbr": None,
        "definition": "Total active employees (often expressed in full-time equivalents, FTE).",
        "formula": "count(active employees)", "direction": None,
        "benchmark": "Read against revenue per employee and plan.",
        "source": "AIHR people analytics 2026",
    },
    "Turnover Rate": {
        "domain": "People", "abbr": None,
        "definition": "Share of the workforce that leaves in a period; segment voluntary vs involuntary.",
        "formula": "departures / average headcount × 100", "direction": "down",
        "benchmark": "Voluntary <10% good; tech runs 15–20%. Retention >85% healthy.",
        "source": "AIHR people analytics 2026",
    },
    "Engagement Score": {
        "domain": "People", "abbr": "eNPS",
        "definition": "Composite of how committed/motivated employees feel; often measured as eNPS (employee NPS).",
        "formula": "eNPS = % promoters − % detractors (0–10 scale)", "direction": "up",
        "benchmark": "eNPS >+20 good, >+50 excellent. Globally only ~23% are engaged.",
        "source": "AIHR people analytics 2026",
    },
    "Time to Hire": {
        "domain": "People", "abbr": "TTH",
        "definition": "Days from a candidate entering the pipeline to offer acceptance (vs time-to-fill from requisition open).",
        "formula": "offer-accept date − application date", "direction": "down",
        "benchmark": "Shorter cuts vacancy cost; benchmark by role/seniority.",
        "source": "AIHR people analytics 2026",
    },
    "Training Hours": {
        "domain": "People", "abbr": None,
        "definition": "Average learning & development hours per employee — an investment-in-people leading indicator.",
        "formula": "Σ training hours / headcount", "direction": "up",
        "benchmark": "Rising L&D correlates with retention and internal mobility.",
        "source": "AIHR people analytics 2026",
    },
    "Open Positions": {
        "domain": "People", "abbr": None,
        "definition": "Currently unfilled approved roles — a capacity-gap and hiring-load signal.",
        "formula": "count(open requisitions)", "direction": "down",
        "benchmark": "Read with time-to-hire and business plan.",
        "source": "AIHR people analytics 2026",
    },
    "Quality of Hire": {
        "domain": "People", "abbr": "QoH",
        "definition": "Downstream value of new hires (performance, ramp, retention) linked back to sourcing channel.",
        "formula": "composite of perf rating, ramp time, 1-yr retention", "direction": "up",
        "benchmark": "Best-practice teams track QoH to steer recruiting spend.",
        "source": "AIHR people analytics 2026",
    },

    "Average Tenure": {
        "domain": "People", "abbr": None,
        "definition": "Average length of time employees have stayed — a retention and institutional-knowledge signal.",
        "formula": "Σ tenure / headcount", "direction": "up",
        "benchmark": "Rising tenure (with healthy hiring) signals stability; very high can signal stagnation.",
        "source": "AIHR people analytics 2026",
    },
    "Cost per Hire": {
        "domain": "People", "abbr": "CPH",
        "definition": "Fully-loaded cost to fill one role (sourcing, agency, referral, recruiter time).",
        "formula": "(internal + external recruiting cost) / hires", "direction": "down",
        "benchmark": "Benchmark by role/seniority; rising CPH with slow time-to-hire flags pipeline issues.",
        "source": "AIHR people analytics 2026",
    },
    "Absenteeism Rate": {
        "domain": "People", "abbr": None,
        "definition": "Share of scheduled work time lost to unplanned absence — a wellbeing and engagement signal.",
        "formula": "absent days / scheduled work days × 100", "direction": "down",
        "benchmark": "<3% typical; sustained rises often precede attrition.",
        "source": "AIHR people analytics 2026",
    },
    "Offer Acceptance Rate": {
        "domain": "People", "abbr": "OAR",
        "definition": "Share of job offers candidates accept — measures offer competitiveness and candidate experience.",
        "formula": "offers accepted / offers extended × 100", "direction": "up",
        "benchmark": "85–90%+ is healthy; below ~80% flags comp or process problems.",
        "source": "AIHR people analytics 2026",
    },
    "Internal Mobility Rate": {
        "domain": "People", "abbr": None,
        "definition": "Share of roles filled by internal moves/promotions rather than external hires.",
        "formula": "internal placements / total placements × 100", "direction": "up",
        "benchmark": "Higher internal mobility correlates with retention and lower hiring cost.",
        "source": "AIHR people analytics 2026",
    },
    "Revenue per Employee": {
        "domain": "People", "abbr": "RPE",
        "definition": "Revenue generated per full-time employee — the headline workforce-productivity metric.",
        "formula": "Revenue / headcount", "direction": "up",
        "benchmark": "Sector-dependent; rising RPE shows efficient scaling. SaaS often $200k–$400k+.",
        "source": "AIHR / SaaS benchmarks 2026",
    },

    # ───────────────────────── Operations ─────────────────────────
    "On-time Delivery": {
        "domain": "Operations", "abbr": "OTD / OTIF",
        "definition": "Share of orders delivered by the promised date (OTIF adds 'in full').",
        "formula": "on-time orders / total orders × 100", "direction": "up",
        "benchmark": "World-class 95–98%+.",
        "source": "Manufacturing KPI guidance 2026",
    },
    "Cycle Time": {
        "domain": "Operations", "abbr": None,
        "definition": "Time to produce one unit / complete one process run; actual vs engineered standard reveals drift.",
        "formula": "process end − process start (per unit)", "direction": "down",
        "benchmark": "Stable and close to takt time; watch variance.",
        "source": "Manufacturing KPI guidance 2026",
    },
    "Defect Rate": {
        "domain": "Operations", "abbr": None,
        "definition": "Share of output that fails quality (inverse of First Pass Yield).",
        "formula": "defective units / total units × 100", "direction": "down",
        "benchmark": "FPY target 95%+ (99%+ auto/medical) → defect rate <5%.",
        "source": "Manufacturing quality KPIs 2026",
    },
    "Capacity Utilization": {
        "domain": "Operations", "abbr": None,
        "definition": "How much of available production capacity is actually used.",
        "formula": "actual output / max possible output × 100", "direction": "up",
        "benchmark": "~85% is often the sweet spot (room for surges/maintenance).",
        "source": "Operations management standard",
    },
    "Production Efficiency": {
        "domain": "Operations", "abbr": "OEE",
        "definition": "Overall Equipment Effectiveness — availability × performance × quality; the gold-standard productivity score.",
        "formula": "Availability × Performance × Quality", "direction": "up",
        "benchmark": "World-class OEE ≈ 85%; many plants sit 40–60%.",
        "source": "OEE / manufacturing standard 2026",
    },
    "Safety Incident Rate": {
        "domain": "Operations", "abbr": "TRIR",
        "definition": "Total Recordable Incident Rate — recordable workplace injuries normalised to hours worked.",
        "formula": "(recordable incidents × 200,000) / hours worked", "direction": "down",
        "benchmark": "Lower is better; reviewed monthly as a strategic safety KPI.",
        "source": "OSHA / manufacturing safety 2026",
    },
    "First Pass Yield": {
        "domain": "Operations", "abbr": "FPY",
        "definition": "Units that pass without rework or scrap on the first attempt.",
        "formula": "good units (no rework) / units entering × 100", "direction": "up",
        "benchmark": "95%+ most industries; 99%+ automotive/medical.",
        "source": "Manufacturing quality KPIs 2026",
    },

    "Quality Rate": {
        "domain": "Operations", "abbr": None,
        "definition": "Share of output meeting quality spec (the quality component of OEE; inverse of defect rate).",
        "formula": "good units / total units × 100", "direction": "up",
        "benchmark": "97%+ for most industries; 99%+ in automotive/medical.",
        "source": "Manufacturing quality KPIs 2026",
    },
    "Throughput": {
        "domain": "Operations", "abbr": None,
        "definition": "Volume of units produced/processed per unit of time — raw output capacity in action.",
        "formula": "units produced / time period", "direction": "up",
        "benchmark": "Read against takt time and demand; stability matters as much as level.",
        "source": "Operations management standard",
    },
    "Unplanned Downtime": {
        "domain": "Operations", "abbr": None,
        "definition": "Hours equipment/lines are unexpectedly stopped — the biggest drag on the availability part of OEE.",
        "formula": "Σ unplanned stop time", "direction": "down",
        "benchmark": "Lower is better; predictive maintenance targets near-zero unplanned stops.",
        "source": "OEE / maintenance standard 2026",
    },
    "Cost per Unit": {
        "domain": "Operations", "abbr": None,
        "definition": "Fully-loaded cost to produce one unit of output — links operations to gross margin.",
        "formula": "total production cost / units produced", "direction": "down",
        "benchmark": "Falls with scale and efficiency; rising unit cost erodes margin.",
        "source": "Operations / cost accounting",
    },
    "Schedule Adherence": {
        "domain": "Operations", "abbr": None,
        "definition": "How closely actual production follows the plan/schedule — on-time completion of planned work.",
        "formula": "on-schedule jobs / total scheduled jobs × 100", "direction": "up",
        "benchmark": "90%+ indicates a reliable, well-balanced plan.",
        "source": "Operations planning standard",
    },
    "Scrap Rate": {
        "domain": "Operations", "abbr": None,
        "definition": "Share of material/output discarded as unusable — direct waste and cost.",
        "formula": "scrapped units / total units × 100", "direction": "down",
        "benchmark": "Lower is better; lean targets continuous reduction toward <2%.",
        "source": "Manufacturing quality KPIs 2026",
    },

    # ───────────────────────── IT ─────────────────────────
    "System Uptime": {
        "domain": "IT", "abbr": None,
        "definition": "Percentage of time systems are available, often expressed as 'nines'.",
        "formula": "available time / total time × 100", "direction": "up",
        "benchmark": "99.9% ('three nines') ≈ 8.8h/yr downtime; 99.99% is strong.",
        "source": "SRE/availability standard",
    },
    "Mean Time to Resolution": {
        "domain": "IT", "abbr": "MTTR",
        "definition": "Average time to recover from an incident/failed deployment — the most reliable DORA metric in the AI era.",
        "formula": "Σ recovery time / number of incidents", "direction": "down",
        "benchmark": "Elite teams recover in <1 hour.",
        "source": "DORA 2026",
    },
    "Security Incidents": {
        "domain": "IT", "abbr": None,
        "definition": "Count of confirmed security events (breaches, intrusions, policy violations) in a period.",
        "formula": "count(confirmed security events)", "direction": "down",
        "benchmark": "Trend to zero; pair with detection/response time.",
        "source": "NIST / security operations",
    },
    "Cloud Cost per User": {
        "domain": "IT", "abbr": None,
        "definition": "Infrastructure/cloud spend divided by active users — a FinOps unit-economics metric.",
        "formula": "cloud spend / active users", "direction": "down",
        "benchmark": "Should fall with scale (economies of scale).",
        "source": "FinOps Foundation",
    },
    "Deployment Frequency": {
        "domain": "IT", "abbr": "DF",
        "definition": "How often code is shipped to production — a DORA throughput metric.",
        "formula": "deployments / period", "direction": "up",
        "benchmark": "Elite: on-demand (multiple/day).",
        "source": "DORA 2026",
    },
    "IT Satisfaction": {
        "domain": "IT", "abbr": None,
        "definition": "Internal satisfaction with IT services/tools (a developer- or employee-experience score).",
        "formula": "survey score (e.g. 1–10)", "direction": "up",
        "benchmark": "Higher reflects platform/DevEx health.",
        "source": "DevEx / platform engineering 2026",
    },
    "Change Failure Rate": {
        "domain": "IT", "abbr": "CFR",
        "definition": "Share of deployments that cause a failure needing rollback/hotfix — a DORA stability metric.",
        "formula": "failed deployments / total deployments × 100", "direction": "down",
        "benchmark": "Elite 0–15%; 2026 top teams <0.5%.",
        "source": "DORA 2026",
    },
    "Lead Time for Changes": {
        "domain": "IT", "abbr": None,
        "definition": "Time from code commit to running in production — a DORA speed metric.",
        "formula": "prod-deploy time − commit time", "direction": "down",
        "benchmark": "Elite: <1 hour.",
        "source": "DORA 2026",
    },

    "Critical Incidents": {
        "domain": "IT", "abbr": "P1",
        "definition": "Count of severity-1 incidents (major outage / security breach) in the period.",
        "formula": "count(P1/Sev-1 incidents)", "direction": "down",
        "benchmark": "Trend toward zero; each one warrants a blameless post-mortem.",
        "source": "SRE / incident management 2026",
    },
    "Cloud Spend": {
        "domain": "IT", "abbr": None,
        "definition": "Total cloud/infrastructure spend in the period — the headline FinOps cost metric.",
        "formula": "Σ cloud + infrastructure invoices", "direction": "down",
        "benchmark": "Should grow slower than usage/revenue; watch unit cost (spend per user).",
        "source": "FinOps Foundation 2026",
    },
    "SLA Compliance": {
        "domain": "IT", "abbr": None,
        "definition": "Share of service-level agreement targets (availability/response/resolution) actually met.",
        "formula": "SLAs met / total SLAs × 100", "direction": "up",
        "benchmark": "95–99%+ depending on tier; misses trigger credits and churn risk.",
        "source": "ITIL / service management 2026",
    },
    "Security Score": {
        "domain": "IT", "abbr": None,
        "definition": "Composite 0–100 security-posture rating (patching, vulnerabilities, controls, config).",
        "formula": "weighted posture index", "direction": "up",
        "benchmark": "Higher is better; pair with open-vulnerability and incident trends.",
        "source": "Security operations 2026",
    },

    # ───────────────────────── Logistics ─────────────────────────
    "Inventory Turnover": {
        "domain": "Logistics", "abbr": None,
        "definition": "How many times inventory is sold and replaced in a period — capital-efficiency of stock.",
        "formula": "COGS / average inventory", "direction": "up",
        "benchmark": "Higher = leaner stock & better cash flow (sector-dependent).",
        "source": "Supply-chain KPI literature 2026",
    },
    "Order Accuracy": {
        "domain": "Logistics", "abbr": None,
        "definition": "Share of outgoing orders fulfilled with no errors (right item/qty/destination).",
        "formula": "error-free orders / total orders × 100", "direction": "up",
        "benchmark": "Target 95%+ to curb returns and cost.",
        "source": "Supply-chain KPI literature 2026",
    },
    "Freight Cost per Unit": {
        "domain": "Logistics", "abbr": None,
        "definition": "Average transportation cost to ship one unit — links logistics execution to the P&L.",
        "formula": "total freight cost / units shipped", "direction": "down",
        "benchmark": "Lower via mode/lane/carrier/packaging optimisation.",
        "source": "Transportation KPI guidance 2026",
    },
    "Warehouse Utilization": {
        "domain": "Logistics", "abbr": None,
        "definition": "Share of usable warehouse space/capacity actually in use.",
        "formula": "used space / total usable space × 100", "direction": "up",
        "benchmark": "~80–85% balances density with pick efficiency.",
        "source": "Warehouse operations standard",
    },
    "Last Mile Delivery Time": {
        "domain": "Logistics", "abbr": None,
        "definition": "Time for the final delivery leg to the customer — a major cost and CX driver.",
        "formula": "delivered time − dispatch time (final leg)", "direction": "down",
        "benchmark": "Faster + reliable; the costliest leg of fulfilment.",
        "source": "Supply-chain KPI literature 2026",
    },
    "Returns Rate": {
        "domain": "Logistics", "abbr": None,
        "definition": "Share of shipped orders returned by customers.",
        "formula": "returned orders / total orders × 100", "direction": "down",
        "benchmark": "Lower is better; spikes flag quality/fit/expectation issues.",
        "source": "Supply-chain KPI literature 2026",
    },
    "Perfect Order Rate": {
        "domain": "Logistics", "abbr": "POR",
        "definition": "Share of orders delivered on time, in full, undamaged, and with correct documentation.",
        "formula": "% on-time × % complete × % undamaged × % correct-docs", "direction": "up",
        "benchmark": "The composite gold standard; 95%+ is strong.",
        "source": "Perfect-order supply-chain literature 2026",
    },
    "Days Inventory Outstanding": {
        "domain": "Logistics", "abbr": "DIO",
        "definition": "Average days inventory is held before sale — the inverse view of turnover.",
        "formula": "(average inventory / COGS) × days in period", "direction": "down",
        "benchmark": "Lower = faster cash conversion (sector-dependent).",
        "source": "Supply-chain finance 2026",
    },

    "On-Time Delivery Rate": {
        "domain": "Logistics", "abbr": "OTD",
        "definition": "Share of orders delivered by the promised date — the core fulfilment-reliability metric.",
        "formula": "on-time deliveries / total deliveries × 100", "direction": "up",
        "benchmark": "World-class 95–98%+; a top driver of customer satisfaction.",
        "source": "Supply-chain KPI literature 2026",
    },
    "Fill Rate": {
        "domain": "Logistics", "abbr": None,
        "definition": "Share of demand met from stock on the first attempt (order/line/unit fill).",
        "formula": "units shipped on time / units ordered × 100", "direction": "up",
        "benchmark": "95%+ balances service level against inventory cost.",
        "source": "Supply-chain KPI literature 2026",
    },
    "Stockout Rate": {
        "domain": "Logistics", "abbr": None,
        "definition": "Share of demand or SKUs unavailable when wanted — lost sales and CX damage.",
        "formula": "stockout events / total demand events × 100", "direction": "down",
        "benchmark": "<2–3%; the direct cost of under-stocking.",
        "source": "Supply-chain KPI literature 2026",
    },
    "Carrying Cost": {
        "domain": "Logistics", "abbr": None,
        "definition": "Total cost of holding inventory (capital, storage, insurance, obsolescence).",
        "formula": "Σ holding costs (typically 20–30% of inventory value/yr)", "direction": "down",
        "benchmark": "Lower frees working capital; trade off against stockout risk.",
        "source": "Supply-chain finance 2026",
    },
    "Avg Lead Time": {
        "domain": "Logistics", "abbr": None,
        "definition": "Average time from order placement to delivery — end-to-end fulfilment speed.",
        "formula": "Σ (delivery date − order date) / orders", "direction": "down",
        "benchmark": "Shorter + consistent; variability hurts as much as the average.",
        "source": "Supply-chain KPI literature 2026",
    },

    # ───────────────────────── ESG ─────────────────────────
    "Carbon Emissions (tCO2)": {
        "domain": "ESG", "abbr": "tCO2e",
        "definition": "Greenhouse-gas emissions in tonnes of CO2-equivalent across Scope 1 (direct), 2 (purchased energy) and 3 (value chain).",
        "formula": "Σ activity data × emission factors (GHG Protocol)", "direction": "down",
        "benchmark": "Under CSRD/ESRS E1, Scope 1–3 disclosure is mandatory in the EU from 2026.",
        "source": "GHG Protocol / CSRD ESRS E1 2026",
    },
    "Renewable Energy %": {
        "domain": "ESG", "abbr": None,
        "definition": "Share of total energy consumption sourced from renewables.",
        "formula": "renewable energy / total energy × 100", "direction": "up",
        "benchmark": "Rising share cuts Scope 2 emissions; many targets aim 100% by 2030.",
        "source": "GHG Protocol / CSRD 2026",
    },
    "Water Consumption (m3)": {
        "domain": "ESG", "abbr": None,
        "definition": "Total freshwater consumed (cubic metres) — a core environmental resource metric (ESRS E3).",
        "formula": "Σ metered water use", "direction": "down",
        "benchmark": "Reduce intensity per unit of output; material in water-stressed areas.",
        "source": "CSRD ESRS E3 2026",
    },
    "Waste Recycled %": {
        "domain": "ESG", "abbr": None,
        "definition": "Share of waste diverted from landfill via recycling/reuse (circularity, ESRS E5).",
        "formula": "recycled waste / total waste × 100", "direction": "up",
        "benchmark": "Higher = stronger circular-economy performance.",
        "source": "CSRD ESRS E5 2026",
    },
    "Diversity Score": {
        "domain": "ESG", "abbr": None,
        "definition": "Composite of workforce diversity & inclusion (gender, ethnicity, pay-gap) — social pillar (ESRS S1).",
        "formula": "composite D&I index", "direction": "up",
        "benchmark": "Higher reflects inclusive workforce; disclose representation & pay gaps.",
        "source": "CSRD ESRS S1 2026",
    },
    "Board Diversity %": {
        "domain": "ESG", "abbr": None,
        "definition": "Share of board seats held by under-represented groups — governance pillar.",
        "formula": "diverse board seats / total seats × 100", "direction": "up",
        "benchmark": "Many frameworks target ≥30–40% gender diversity.",
        "source": "Governance / CSRD 2026",
    },
    "Scope 1 / 2 / 3": {
        "domain": "ESG", "abbr": None,
        "definition": "GHG Protocol emission boundaries: Scope 1 = direct (owned sources); Scope 2 = purchased energy; Scope 3 = all other value-chain emissions (usually the largest).",
        "formula": "per-scope: Σ activity × emission factor", "direction": "down",
        "benchmark": "Scope 3 is mandatory under CSRD using the GHG Protocol as the basis.",
        "source": "GHG Protocol / CSRD 2026",
    },
    "CSRD": {
        "domain": "ESG", "abbr": "CSRD",
        "definition": "EU Corporate Sustainability Reporting Directive — mandates detailed, audited sustainability disclosure for 50,000+ companies.",
        "formula": None, "direction": None,
        "benchmark": "Reporting on ESRS standards (E1 climate is always required); phased from 2024–2028.",
        "source": "EU CSRD 2026",
    },
    "Double Materiality": {
        "domain": "ESG", "abbr": None,
        "definition": "CSRD principle: disclose both how sustainability issues affect the business (financial) and how the business affects people/planet (impact).",
        "formula": None, "direction": None,
        "benchmark": "Drives the topics a company must report under ESRS.",
        "source": "EU CSRD / ESRS 2026",
    },

    "ESG Score": {
        "domain": "ESG", "abbr": None,
        "definition": "Composite 0–100 rating blending environmental, social and governance performance.",
        "formula": "weighted blend of E, S and G pillar scores", "direction": "up",
        "benchmark": "Higher is better; methodology varies by rater — disclose the basis.",
        "source": "ESG ratings methodology 2026",
    },
    "Scope 1 Emissions": {
        "domain": "ESG", "abbr": None,
        "definition": "Direct GHG emissions from owned/controlled sources (combustion, company vehicles, processes).",
        "formula": "Σ direct activity data × emission factors", "direction": "down",
        "benchmark": "Mandatory under CSRD/ESRS E1; the most directly controllable scope.",
        "source": "GHG Protocol / CSRD ESRS E1 2026",
    },
    "Scope 2 Emissions": {
        "domain": "ESG", "abbr": None,
        "definition": "Indirect GHG emissions from purchased energy (electricity, steam, heating/cooling).",
        "formula": "Σ purchased energy × grid emission factors", "direction": "down",
        "benchmark": "Cut fastest by renewable energy procurement; mandatory under CSRD.",
        "source": "GHG Protocol / CSRD ESRS E1 2026",
    },
    "Scope 3 Emissions": {
        "domain": "ESG", "abbr": None,
        "definition": "All other value-chain emissions (suppliers, logistics, product use, travel) — usually the largest share.",
        "formula": "Σ 15 upstream/downstream categories × emission factors", "direction": "down",
        "benchmark": "Often 70–90% of the footprint; Scope 3 disclosure now required under CSRD.",
        "source": "GHG Protocol / CSRD ESRS E1 2026",
    },
    "Emissions Intensity": {
        "domain": "ESG", "abbr": None,
        "definition": "Emissions normalised to business size (per unit revenue/output) — enables fair comparison and decoupling.",
        "formula": "total tCO2e / $M revenue (or unit of output)", "direction": "down",
        "benchmark": "Falling intensity shows emissions decoupling from growth.",
        "source": "GHG Protocol / CSRD 2026",
    },
    "Gender Pay Gap": {
        "domain": "ESG", "abbr": None,
        "definition": "Difference in average pay between genders — a core social-pillar (ESRS S1) disclosure.",
        "formula": "(avg male pay − avg female pay) / avg male pay × 100", "direction": "down",
        "benchmark": "Toward 0%; disclosure mandatory under CSRD and the EU Pay Transparency Directive.",
        "source": "CSRD ESRS S1 / EU Pay Transparency 2026",
    },
    "Community Investment": {
        "domain": "ESG", "abbr": None,
        "definition": "Spend/contributions to community and social programmes — a social-pillar commitment metric.",
        "formula": "Σ community/charitable investment", "direction": "up",
        "benchmark": "Often benchmarked as a % of pre-tax profit; report outcomes, not just spend.",
        "source": "CSRD ESRS S3 2026",
    },

    # ───────────────────────── Risk ─────────────────────────
    "Risk Score": {
        "domain": "Risk", "abbr": None,
        "definition": "Composite 0–100 health-of-risk score blending revenue volatility, anomaly count, and concentration.",
        "formula": "100 − (volatility×1.5 + anomalies×5 + concentration×0.4)", "direction": "up",
        "benchmark": "≥70 Low risk, 50–70 Moderate, <50 High.",
        "source": "IntelAI insights engine",
    },
    "Anomaly Detection": {
        "domain": "Risk", "abbr": None,
        "definition": "Statistical flagging of metric readings that deviate sharply from their trend (e.g. a revenue dip or churn spike).",
        "formula": "z-score / robust outlier test on the series", "direction": None,
        "benchmark": "Each anomaly is a watch-item to investigate.",
        "source": "IntelAI insights engine",
    },

    # ───────────────────────── Method / AI ─────────────────────────
    "KPI": {
        "domain": "Method", "abbr": "KPI",
        "definition": "Key Performance Indicator — a quantified measure tracking progress against an objective.",
        "formula": None, "direction": None,
        "benchmark": "Good KPIs are specific, comparable over time, and tied to a decision.",
        "source": "Management standard",
    },
    "RAG": {
        "domain": "Method", "abbr": "RAG",
        "definition": "Retrieval-Augmented Generation — the AI retrieves your real data/documents first, then answers from that evidence (with citations) instead of from memory.",
        "formula": None, "direction": None,
        "benchmark": "Cuts hallucination; the 2026 standard is hybrid + reranking + graph.",
        "source": "RAG production patterns 2026",
    },
    "Persona-Routed RAG": {
        "domain": "Method", "abbr": None,
        "definition": "IntelAI's approach: the copilot adopts a role persona (CEO/CFO/…) that scopes which data it may read (RBAC) and how it answers — grounded, role-appropriate, cited.",
        "formula": None, "direction": None,
        "benchmark": "Combines access control with retrieval for safe, relevant answers.",
        "source": "IntelAI STRATEGY",
    },
    "GraphRAG": {
        "domain": "Method", "abbr": None,
        "definition": "Retrieval over an entity/relationship graph (not just text chunks) so the AI can answer multi-hop, relationship questions across the KPI set.",
        "formula": None, "direction": None,
        "benchmark": "Knowledge-graph RAG cut hallucination ~62% in 2026 production benchmarks.",
        "source": "RAG production patterns 2026",
    },
    "Hybrid Retrieval": {
        "domain": "Method", "abbr": None,
        "definition": "Combines dense vector (semantic) search with BM25 keyword search, fused (RRF), to catch both meaning and exact terms.",
        "formula": "RRF(dense ranks, BM25 ranks)", "direction": None,
        "benchmark": "The 2026 default; outperforms either method alone.",
        "source": "RAG production patterns 2026",
    },
    "Reranking": {
        "domain": "Method", "abbr": None,
        "definition": "A cross-encoder re-scores the top retrieved candidates so the most relevant evidence is actually used — stops confident answers from weak first retrievals.",
        "formula": None, "direction": None,
        "benchmark": "Cross-encoder/critic reranking is standard for groundedness in 2026.",
        "source": "RAG production patterns 2026",
    },
    "Groundedness": {
        "domain": "Method", "abbr": None,
        "definition": "Whether every claim in an answer is supported by the retrieved sources — the core anti-hallucination measure.",
        "formula": "supported claims / total claims", "direction": "up",
        "benchmark": "IntelAI gates its eval on groundedness (cite or don't claim).",
        "source": "IntelAI eval / RAG patterns 2026",
    },
}


# ── Helpers ─────────────────────────────────────────────────────────────────
def get_term(term: str) -> Optional[Dict[str, Any]]:
    """Case-insensitive exact, then abbreviation, then substring match."""
    if not term:
        return None
    t = term.strip().lower()
    for name, e in GLOSSARY.items():
        if name.lower() == t or (e.get("abbr") and e["abbr"].lower() == t):
            return {"term": name, **e}
    for name, e in GLOSSARY.items():
        if t in name.lower() or (e.get("abbr") and t in e["abbr"].lower()):
            return {"term": name, **e}
    return None


def for_domain(domain: Optional[str] = None) -> List[Dict[str, Any]]:
    """All glossary entries, optionally filtered to a domain (case-insensitive)."""
    out = []
    for name, e in GLOSSARY.items():
        if domain and e["domain"].lower() != domain.lower():
            continue
        out.append({"term": name, **e})
    return out


def as_knowledge_docs() -> List[Dict[str, str]]:
    """Render the glossary as RAG knowledge docs so the copilot can cite definitions."""
    docs = []
    for name, e in GLOSSARY.items():
        parts = [f"{name}" + (f" ({e['abbr']})" if e.get("abbr") else "") + f" — {e['domain']} domain.",
                 f"Definition: {e['definition']}"]
        if e.get("formula"):
            parts.append(f"Formula: {e['formula']}.")
        if e.get("direction"):
            parts.append(f"Better when {'higher' if e['direction'] == 'up' else 'lower'}.")
        if e.get("benchmark"):
            parts.append(f"2026 benchmark: {e['benchmark']}")
        parts.append(f"Source: {e['source']}.")
        docs.append({
            "title": f"Glossary: {name}" + (f" ({e['abbr']})" if e.get("abbr") else ""),
            "content": " ".join(parts),
            "source": f"glossary/{e['domain'].lower()}/{name.lower().replace(' ', '_')}.md",
            "category": e["domain"],
        })
    return docs
